spring.application.name=springGestionDesStagiaires

# connection spring <-> database
spring.datasource.url=jdbc:mysql://localhost:3306/newmydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
server.port=8081

#update keeps the table and update it / create /create-drop delete the existing one and create new one
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL commands in your console (Great for learning)
spring.jpa.show-sql=true
